<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
		$this->createTable('email_blacklist', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'unsigned' => '0',
              'primary' => '1',
              'autoincrement' => '1',
             ),
             'email' => 
             array(
              'type' => 'string',
              'length' => '255',
              'fixed' => '',
              'primary' => '',
              'notnull' => '1',
              'autoincrement' => '',
             ),
             'added_ts' => 
             array(
              'type' => 'timestamp',
              'primary' => '',
              'notnull' => '1',
              'autoincrement' => '',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8mb4_unicode_ci',
             ));
    }

    public function down()
    {
		$this->dropTable('email_blacklist');
    }
}