<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OutputInterface extends BaseOutputInterface
{
    public function setUp()
    {
        $this->hasMany('Display as Users', array(
            'local' => 'interface',
            'foreign' => 'interface',
        ));
    }

}
