<?php

/**
 * Planlove
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
class Planlove extends BasePlanlove
{
    public function setUp() {
        parent::setUp();
        $this->hasOne('Accounts as Lover', array('local' => 'lover_id', 'foreign' => 'userid'));
        $this->hasOne('Accounts as Lovee', array('local' => 'lovee_id', 'foreign' => 'userid'));
    }
}
