<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Style extends BaseStyle
{
    public function setUp()
    {
        $this->hasMany('Display as Users', array(
            'local' => 'style',
            'foreign' => 'style',
        ));
    }

}
